@startuml

participant "User" as U
participant "Controller" as C
participant "Service" as S
participant "Repository" as R
participant "Database" as D

U -> C: Request
C -> S: Request
S -> R: Request

R -> D: Request

D -> R: Response
R -> S: Response
S -> C: Response
C -> U: Response


@enduml
