FROM openjdk:17-alpine
LABEL authors="sebastiaofidencio"


RUN apk add --no-cache bash \
    && apk add --no-cache curl \
    && apk add --no-cache iputils \
    && apk add --no-cache vim \
    && apk add --no-cache htop
#development, production
WORKDIR /app

COPY target/*.jar /app/app.jar
CMD ["java","-Dspring.profiles.active=production", "-jar", "app.jar"]
#CMD ["/bin/sh", "-c", "bash"]